typedef struct noAvl{
    int elem;
    int fb;
    struct noAvl *esq;
    struct noAvl *dir;
    struct noAvl *pai;
}noAvl;
void inicializarAvl(noAvl **avl);
int verif_vaziaAvl(noAvl *avl);
int alturaAvl(noAvl *avl);
void refazerBalanAvl(noAvl **avl);
void rotacaoEsqAvl(noAvl **avl);
void rotacaoDirAvl(noAvl **avl);
void inserirAvl(noAvl **avl,int elem);
noAvl* buscaNoAvl(noAvl **avl,int elem);
noAvl* buscaAntecessorAvl(noAvl **avl,int elem,noAvl *ant);
noAvl* buscaSubstAvl(noAvl **avl,int elem);
void removerNoAvl(noAvl **avl,int elem);
void imprimirPreOrdemAvl(noAvl **avl);
void imprimirEmOrdemAvl(noAvl **avl);
void imprimirPosOrdemAvl(noAvl **avl);
void salvarEmArq(noAvl *avl);
void removerEmArq(int elem);
noAvl* recuperarAvlArq(noAvl **avl,FILE *arq);
void salvarAvlArq(noAvl **avl,FILE *arq);
int EhBB(noAvl **avl);
int verifEsq(noAvl *avl);
int verifDir(noAvl *avl);
int EhAvl(noAvl **avl);
